site_name: DataEntry Documentation
nav:
  - Home: index.md
  - Schema:
      - What is a JSON Schema?: schema/jsonschema.md
      - Extending the Schema: schema/extend.md
      - Render Methods:
          - Main Methods: schema/rendering.md
          - Additional Methods: schema/additional.md
      - Dynamic Functions: schema/dynamic.md
      - Validation: schema/validation.md
  - Components: components.md
  - Extending: extending.md
  - Lookup: lookup.md
  - Messages: messages.md
  - Translations: translations.md

theme:
  features:
    - content.code.annotate
    - content.code.copy
  name: material
  language: en
  palette:
    primary: 'blue'
    accent: 'light blue'

markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.snippets:
      base_path: ['./', 'docs/snippets/']
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_dir: documentation